// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"context"
)

type Querier interface {
	GetUserByEmail(ctx context.Context, email string) (*User, error)
	GetUsers(ctx context.Context) ([]*User, error)
	InsertUser(ctx context.Context, arg InsertUserParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
